[tool.black]
line-length = 88
target-version = ["py311"]
include = "src|tests"

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I"]  # Errores b√°sicos + imports
ignore = []

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
check_untyped_defs = true
disallow_untyped_defs = false
mypy_path = ["src"]